
include=~/.cache/wal/colors-fuzzel.ini

[main]
font=JetBrainsMono Nerd Font:size=12
icon-theme=Papirus-Dark
icons-enabled=yes


width=50
lines=8
line-height=24
prompt=""

# Verhalten
layer=overlay
exit-on-keyboard-focus-loss=yes
match-mode=fzf

[border]
width=2
radius=12